# This is a basic workflow to help you get started with Actions

name: Rust CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "rust2018" ]
  pull_request:
    branches: [ "main", "rust2018" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.77.0", stable, nightly]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5 # https://github.com/marketplace/actions/checkout
      - uses: actions-rs/toolchain@v1 # https://github.com/marketplace/actions/rust-toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v2 # https://github.com/marketplace/actions/rust-cache
        with:
          key: "${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions-rs/cargo@v1 # https://github.com/marketplace/actions/rust-cargo
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --all-features --verbose
      - uses: actions-rs/cargo@v1 
        with:
          command: test
          toolchain: ${{ matrix.rust }}
          args: --all-features --verbose
      - uses: actions-rs/cargo@v1 
        with:
          command: clippy
          toolchain: ${{ matrix.rust }}
          args: -- -D warnings --all-features --all-targets
      - uses: actions-rs/cargo@v1 
        with:
          command: doc
          toolchain: ${{ matrix.rust }}
          args:  --verbose --all-features --document-private-items
      - uses: actions-rs/cargo@v1 
        with:
          command: fmt
          toolchain: ${{ matrix.rust }}
          args:  -- --check
      - uses: actions-rs/cargo@v1 
        with:
          command: publish
          toolchain: ${{ matrix.rust }}
          args:  --dry-run

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
